# GitHub action to build repos that are dependent on this library
name: Build Dependent Repos

on: 
  release:
    types: [published,edited]
  workflow_dispatch:
    inputs:
      message:
        description: Message to display in job summary
        required: false
        type: string

jobs:
  build-dependent-repos:
    strategy:
      matrix:
        include:
          - name: Trigger build on Wireless-Signal-Tester
            repo: Wireless-Signal-Tester
          - name: Trigger build on Sensor-Repeater
            repo: Sensor-Repeater
          - name: Trigger build on TI-RSLK-Example-Sketches
            repo: TI-RSLK-Example-Sketches
          - name: Trigger build on Wireless-Sensor-Receiver-Hub
            repo: Wireless-Sensor-Receiver-Hub

    name: call-compile-sketches-workflow
    uses: Andy4495/.github/.github/workflows/build-dependent-repos.yml@main
    with:
      message: ${{ inputs.message }}
      repo-name: ${{ matrix.repo }}
    secrets: inherit
        
            